# Configuration using colors from the Set1 palette. Right now the first six are used according to ColorBrewer2
# Colors already approved for dashboard but not used: "#46196b", "#FFE30B"
KP.1.1.X:
  name: "KP.1.1.X"
  members:
    - "KP.1.1.X"
  parent: "JN.1.X"

KP.3.1.1.X:
  name: "KP.3.1.1.X"
  members:
    - "KP.3.1.1.X"
  parent: "KP.3.X"
  
LB.1.X:
  name: "LB.1.X"
  members:
    - "LB.1.X"
  parent: "JN.1.X"

KP.3.X:
  name: "KP.3.X"
  members:
    - "KP.3.X"
  parent: "JN.1.X"

JN.1.16.X:
  name: "JN.1.16.X"
  members:
    - "JN.1.16.X"
  parent: "JN.1.X"

KP.2.X:
  name: "KP.2.X"
  members:
    - "KP.2.X"
  parent: "JN.1.X"

# JN.1.11.X:
#   name: "JN.1.11.X"
#   members:
#     - "JN.1.11.X"
#   parent: "JN.1.X"

# KQ.1.X:
#   name: "KQ.1.X"
#   members:
#     - "KQ.1.X"
#   parent: "JN.1.X"

# JN.1.4.X:
#   name: "JN.1.4.X"
#   members:
#     - "JN.1.4.X"
#   parent: "JN.1.X"

# JN.1.7.X:
#   name: "JN.1.7.X"
#   members:
#     - "JN.1.7.X"
#   parent: "JN.1.X"

JN.1.X:
  name: "JN.1.X"
  members:
    - "JN.1.X"
    - "JN.1.7.X"
    - "KQ.1.X"
    - "JN.1.4.X"
    - "JN.1.11.X"
  parent: "BA.2.86.X"

BA.2.86.X:
  name: "BA.2.86.X"
  members:
    - "BA.2.86.X"
  color: "#808000"

HV.1.X:
  name: "HV.1.X"
  members:
    - "HV.1.X"
  parent: "XBB.1.9.X"

EG.5.X:
  name: "EG.5.X"
  members:
    - "EG.5.X"
  parent: "XBB.1.9.X"

XBB.1.9.X:
  name: "XBB.1.9.X"
  members:
    - "XBB.1.9.X"
  color: "#ffb731"

XBB.2.3.X:
  name: "XBB.2.3.X"
  members:
    - "XBB.2.3.X"
  parent: "XBB.X"

XBB.1.16.X:
  name: "XBB.1.16.X"
  members:
    - "XBB.1.16.X"
  parent: "XBB.X"
  
XBB.1.5.X:
  name: "XBB.1.5.X"
  members:
    - "XBB.1.5.X"
  parent: "XBB.X"

XBB.X:
  name: "XBB.X"
  members:
    - "XBB.X"
  color: "#e41a1c"

# BQ.1.1.X:
#   name: "BQ.1.1.X"
#   members:
#     - "BQ.1.1.X"
#   parent: "BA.5"

BQ.1.X:
  name: "BQ.1.X"
  members:
    - "BQ.1.1.X"
    - "BQ.1.X"
  parent: "BA.5"

# BF.7.X:
#   name: "BF.7.X"
#   members:
#     - "BF.7.X"
#   parent: "BA.5"

BA.5:
  name: "BA.5.X"
  members:
    - "BF.7.X"
    - "BA.5.X"
  color: "#984ea3"

BA.4:
  name: "BA.4.X"
  members:
    - "BA.4.X"
    - "BA.4.6"
  color: "#ff7f00"

# BA.2.12.X:
#   name: "BA.2.12.X"
#   members:
#     - "BA.2.12.X"
#   parent: "BA.2.X"

BA.2.X:
  name: "BA.2.X"
  members:
    - "BA.2.12.X"
    - "BA.2.X"
    - "BN.1.X"
  color: "#4daf4a"

# BA.1.1.X:
#   name: "BA.1.1.X"
#   members:
#     - "BA.1.1.X"
#   parent: "BA.1"

BA.1:
  name: "BA.1"
  members:
    - "BA.1.1.X"
    - "BA.1"
    - "B.1.1.529"
  color: "#377eb8"

Delta:
  name: "Delta"
  members:
    - "AY.113"
    - "AY.100"
    - "AY.20"
    - "AY.25"
    - "AY.3"
    - "AY.44"
    - "AY.119"
    - "AY.3.1"
    - "AY.103"
    - "AY.46.4"
    - "AY.25.1"
    - "AY.116"
    - "AY.43.4"
    - "Other Delta sub-lineages"
  color: "#3b3c3d"
  
  
Recombinants:
  name: "Other recombinants"
  members:
    - "Recombinants"
  color: "#6A6C6E"

Other:
  name: "Other"
  members: null
  color: "#DDDDDD"
